#!/usr/bin/env python3

"""shebang"""

def main():

    #what is your name?
    name = input("What is your name?")
    
    #what day of the week is it?
    day_of_week = input("What day of the week is it?")


    #print statement: Hello, <name>! Happpy <day of the week>!
    print(f"Hello, {name}! Happy {day_of_week}!")

main()
